services:
  scraper:
    build: ./scraper
    ports:
      - "6800:6800"
    volumes:
      - ./output:/output
      - ./scrapyd_data:/var/lib/scrapyd
    environment:
      MONGO_URI: mongodb://root:password@mongo:27017/
      MONGO_DB: search-engine

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false
