services:
  scraper:
    build: ./scraper
    ports:
      - "6800:6800"
    volumes:
      - ./output:/output
      - ./scrapyd_data:/var/lib/scrapyd
    environment:
      ENGINE_HOST: http://engine-tt:3000

  engine-tt:
    build: ./engine-tt
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./index:/index
      - ./page-index:/page-index

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_ENGINE_HOST=http://localhost:3000
    ports:
      - "4000:3000"
